version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file: .env.dev
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data: